services:
  terminator:
    build: .
    ports:
      - "3001:3001"
      - "3000:3000"  # Web UI access
    volumes:
      - ./backend/workspace:/app/backend/workspace
      - ./backend/uploads:/app/backend/uploads
      - ./backend/data:/app/backend/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped
    stdin_open: true
    tty: true