version: '3.8'

services:
  terminator:
    build: .
    container_name: terminator-webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ # optional
      - KEYBOARD=en-us-qwerty # optional
      - TITLE=Terminator # optional
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock # optional for Docker access
    ports:
      - 3000:3000   # Terminator web interface
      - 3001:3001   # Webtop web interface
    restart: unless-stopped
    shm_size: "1gb" # Increase shared memory for browser operations
    security_opt:
      - seccomp:unconfined # Optional: for advanced browser features
    cap_add:
      - SYS_ADMIN # Optional: for browser sandbox

  # Optional: Redis for session storage (if needed)
  redis:
    image: redis:alpine
    container_name: terminator-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: